services:
  postgres-pix:
    image: postgres:15-alpine
    container_name: db_pix
    restart: unless-stopped
    environment:
      POSTGRES_USER: pix_user
      POSTGRES_PASSWORD: pix_password
      POSTGRES_DB: pix_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq-pix:
    image: rabbitmq:3-management-alpine
    container_name: broker_pix
    restart: unless-stopped
    ports:
      - "5672:5672"   # Porta para as aplicações (Java/Node/.NET) se conectarem
      - "15672:15672" # Porta da Interface Gráfica (Painel de Administração)

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PixPlatform@2026 # Senha forte obrigatória no SQL Server
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  postgres_data:
  sqlserver_data: # Adicionamos o volume para não perder os dados se o container reiniciar
