services:
  postgres-pix:
    image: postgres:15-alpine
    container_name: db_pix
    restart: unless-stopped
    environment:
      POSTGRES_USER: pix_user
      POSTGRES_PASSWORD: pix_password
      POSTGRES_DB: pix_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: