# Etapa 1: Construção (Build)
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: Servidor de Produção (NGINX)
FROM nginx:alpine
# Copia os arquivos gerados pelo Angular para a pasta pública do NGINX
COPY --from=build /app/dist/pix-frontend/browser /usr/share/nginx/html
EXPOSE 80